language: node_js
node_js:
    - "8.11"
script: jshint app.js

before_script:
    - npm install
    - npm install -g jshint
    - npm install -g express
    - npm install -g firebase
    - npm test 

after_success:
- firebase deploy --token $FIREBASE_TOKEN
  