language: node_js
node_js:
    - "8.11"


before_script:
    ##- npm install
    - npm install -g jshint
  ##  - npm install -g express
   # - npm install -g firebase
   # - npm install -g firebase-tools
    - npm test 

script: jshint functions/index.js

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN