language: node_js
node_js:
    - "8.11"
script: jshint app.js

before_script:
    - npm install
    - npm install -g jshint
    - npm install -g express
    - npm test 

deploy:
  provider: azure_web_apps
  verbose: true
  